
version: '{build}'

os:
    - Visual Studio 2017

before_build:
    - cmake -G "Visual Studio 15 2017 Win64" .

build_script:
    - mkdir build
    - cmake -G "Visual Studio 15 2017 Win64" -D BOOST_ROOT="C:\Libraries\boost_1_67_0" ..
    - cmake --build . --config Release

test_script:
    - ctest -C Release --output-on-failure
