
version: '{build}'

os:
    - Visual Studio 2017

before_build:
    - cmake -G "Visual Studio 15 2017 Win64" .

build_script:
    - mkdir build
    - cmake -G "Visual Studio 15 2017 Win64" ..
    - cmake --build . --config Release

test_script:
    - ctest -C Release --output-on-failure
