
version: '{build}'

os:
    - Visual Studio 2017

build_script:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 15 2017 Win64" -DBOOST_ROOT=C:\Libraries\boost_1_67_0 ..
    - cmake --build . --config Release

test_script:
    - ctest -C Release --output-on-failure
