language: cpp

dist: trusty
sudo: required

branches:
  only:
    - develop

git:
    depth: 3

before_install:
  - export BOOSTVER=1_66_0
  - wget https://downloads.sourceforge.net/project/boost/boost/${BOOSTVER//_/.}/boost_${BOOSTVER}.tar.bz2
  - tar xf boost_${BOOSTVER}.tar.bz2
  - export BOOSTDIR="${PWD}/boost/boost_${BOOSTVER}"
  - wget https://github.com/cpputest/cpputest/releases/download/v3.8/cpputest-3.8.tar.gz
  - tar xf cpputest-3.8.tar.gz
  - cd ./cpputest-3.8
  - CC=gcc-6 CXX=g++-6 ./configure --enable-std-cpp11 --prefix=/usr --disable-memory-leak-detection
  - make
  - sudo make install
  - cd ..
  - gem install coveralls-lcov
  - sudo apt-get -qq update

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - g++-6
      - g++-7
      - lcov

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=g++-5

    - os: linux
      compiler: gcc
      env: COMPILER=g++-6

    - os: linux
      compiler: gcc
      env: COMPILER=g++-7

    - os: linux
      compiler: clang
      env: COMPILER=clang++

script:
  - make CXX=$COMPILER COVERAGE="--coverage" CPPFLAGS="-I ${BOOSTDIR}" lib
  - cat build/buildinfo.h
  - make CXX=$COMPILER COVERAGE="--coverage" CPPFLAGS="-I ${BOOSTDIR}" test

after_success:
  - lcov -c --no-external -d . -o build/coverage.info
  - coveralls-lcov build/coverage.info
