language: cpp

dist: trusty
sudo: required
os: linux

branches:
  only:
    - develop

git:
    depth: 3

before_install:
  - export BOOSTVER=1_66_0
  - export BOOSTDIR="${PWD}/boost_${BOOSTVER}"
  - wget https://downloads.sourceforge.net/project/boost/boost/${BOOSTVER//_/.}/boost_${BOOSTVER}.tar.bz2
  - tar xf boost_${BOOSTVER}.tar.bz2
  - wget https://github.com/cpputest/cpputest/releases/download/v3.8/cpputest-3.8.tar.gz
  - tar xf cpputest-3.8.tar.gz
  - cd ./cpputest-3.8
  - CC=gcc-6 CXX=g++-6 CXXFLAGS="-O2" CFLAGS="-O2" ./configure --enable-std-cpp11 --prefix=/usr --disable-memory-leak-detection
  - make
  - sudo make install
  - cd ..
  - gem install coveralls-lcov
  - sudo apt-get -qq update

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - g++-6
      - g++-7
      - g++-8
      - lcov
      - valgrind

matrix:
  include:
    - env:
          - MODE=RELEASE
          - COMPILER="gcc-5 gcc-6 gcc-7 gcc-8 clang"

    - env:
          - MODE=DEBUG
          - COMPILER="gcc-7"

    - env:
          - MODE=PROFILING
          - COMPILER="gcc-7"

script:
  - ./bin/travis.ch
