language: cpp

dist: trusty
sudo: required
os: linux

branches:
  only:
    - develop

git:
    depth: 3

before_install:
  - export BOOSTVER=1_66_0
  - export BOOSTDIR="${PWD}/boost_${BOOSTVER}"
  - wget -qO- https://downloads.sourceforge.net/project/boost/boost/${BOOSTVER//_/.}/boost_${BOOSTVER}.tar.bz2 | tar xj
  - export CPPUTESTVER=3.8
  - wget -qO- https://github.com/cpputest/cpputest/releases/download/v3.8/cpputest-${CPPUTESTVER}.tar.gz | tar xz
  - cd ./cpputest-${CPPUTESTVER}
  - CC=gcc-6 CXX=g++-6 CXXFLAGS="-O2" CFLAGS="-O2" ./configure --enable-std-cpp11 --prefix=/usr --disable-memory-leak-detection
  - sudo make install
  - cd ..
  - gem install coveralls-lcov
  - sudo apt-get -qq update
  - sudo pip install --upgrade cppclean
  - export CPPCHECKVER=1.82
  - wget -qO- https://github.com/danmar/cppcheck/archive/${CPPCHECKVER}.tar.gz | tar xz
  - sudo make -C ./cppcheck-${CPPCHECKVER} SRCDIR=build CFGDIR=/usr/share/cppcheck/cfg HAVE_RULES=yes install

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - g++-6
      - g++-7
      - lcov
      - valgrind

matrix:
  include:
    - env:
          - MODE=RELEASE
          - COMPILER="gcc-5 gcc-6 gcc-7 clang"

    - env:
          - MODE=DEBUG
          - COMPILER="gcc-7"

    - env:
          - MODE=PROFILING
          - COMPILER="gcc-7"

    - env:
          - MODE=ANALYSIS

script:
  - ./bin/travis.sh
