language: cpp

dist: trusty
sudo: required

branches:
  only:
    - develop

git:
    depth: 3

before_install:
  - wget https://github.com/cpputest/cpputest/releases/download/v3.8/cpputest-3.8.tar.gz
  - tar xf cpputest-3.8.tar.gz
  - cd ./cpputest-3.8
  - CC=gcc-6 CXX=g++-6 ./configure --enable-std-cpp11 --prefix=/usr --disable-memory-leak-detection
  - make
  - sudo make install
  - cd ..
  - gem install coveralls-lcov

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - g++-6
      - lcov

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=g++-5

    - os: linux
      compiler: gcc
      env: COMPILER=g++-6

script:
  - make CXX=$COMPILER COVERAGE="--coverage" lib
  - cat build/buildinfo.h
  - make CXX=$COMPILER COVERAGE="--coverage" test

after_success:
  - lcov -c --no-external -d . -o build/coverage.info
  - coveralls-lcov build/coverage.info
