language: cpp

dist: trusty
sudo: required
os: linux

branches:
  only:
    - develop

git:
    depth: 3

before_install:
  - sudo apt-get remove -y libboost-all-dev
  - sudo apt-get autoremove -y
  - sudo apt-get -qq update
  - export BOOSTVER=1_66_0
  - export BOOSTDIR="${PWD}/boost_${BOOSTVER}"
  - wget -qO- https://downloads.sourceforge.net/project/boost/boost/${BOOSTVER//_/.}/boost_${BOOSTVER}.tar.bz2 | tar xj
  - cd ${BOOSTDIR}
  - ./bootstrap.sh && ./b2 --with-test link=static
  - find ./stage -name 'libboost_unit_test*.a' -exec cp '{}' . \;
  - cd ..
  - gem install coveralls-lcov
  - sudo pip install --upgrade cppclean
  - export CPPCHECKVER=1.82
  - wget -qO- https://github.com/danmar/cppcheck/archive/${CPPCHECKVER}.tar.gz | tar xz
  - sudo make -C ./cppcheck-${CPPCHECKVER} SRCDIR=build CFGDIR=/usr/share/cppcheck/cfg HAVE_RULES=yes install
  - export OCLINTVER=0.13
  - wget -qO- https://github.com/oclint/oclint/releases/download/v${OCLINTVER}/oclint-${OCLINTVER}-x86_64-linux-3.13.0-125-generic.tar.gz | tar xz
  - export OCLINT_HOME="$HOME/oclint-${OCLINTVER}"
  - export PATH="${PATH}:${PWD}/oclint-${OCLINTVER}/bin"
  - echo | g++ -E -v -
  - echo | clang++ -E -v -

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - g++-6
      - g++-7
      - lcov
      - valgrind

matrix:
  include:
    - env:
          - MODE=RELEASE
          - COMPILER="g++-7 g++-6 g++-5 clang++"

    - env:
          - MODE=DEBUG
          - COMPILER="g++-7"

    - env:
          - MODE=PROFILING
          - COMPILER="g++-7"

    - env:
          - MODE=ANALYSIS

script:
  - ./bin/travis.sh
