language: cpp

dist: trusty
sudo: required
os: linux

branches:
  only:
    - develop

git:
    depth: 3

install:
  - export MAKEFLAGS='-j 2'
  - sudo apt-get remove -y libboost-all-dev
  - sudo apt-get autoremove -y
  - sudo apt-get -qq update
  - export BOOSTVER=1_67_0
  - export BOOSTDIR="${PWD}/boost_${BOOSTVER}"
  - wget -qO- https://downloads.sourceforge.net/project/boost/boost/${BOOSTVER//_/.}/boost_${BOOSTVER}.tar.bz2 | tar xj
  - export OCLINTVER=0.13
  - export OCLINT_HOME="$HOME/oclint-${OCLINTVER}"
  - export PATH="${PATH}:${PWD}/oclint-${OCLINTVER}/bin"
  - ./bin/travis-setup.sh
  - echo | g++ -E -v -
  - echo | clang++ -E -v -

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - g++-6
      - g++-7
      - cmake
      - lcov
      - valgrind

matrix:
  include:
    - env:
          - MODE=RELEASE
          - COMPILER="g++-7 g++-6 g++-5 clang++"

    - env:
          - MODE=DEBUG
          - COMPILER="g++-7"

    - env:
          - MODE=PROFILING
          - COMPILER="g++-7"

    - env:
          - MODE=ANALYSIS

script:
  - ./bin/travis.sh
